---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: exampleSite/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: exampleSite/content/products
  label: Products
  create: all
  match: "**/*"
- type: directory
  path: exampleSite/content/blog
  label: Blog
  create: all
  match: "**/*"
upload_dir: exampleSite/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_VERSION=0.97.0
  - NODE_VERSION=0.17.9
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/hugo:node16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
version: 0.80.0
